language: node_js
node_js:
- '10'
- '8'
services:
  - xvfb
notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    on_pull_requests: false
    rooms:
      - secure: toSawRvOCizAfidsGebrti5oXSaXf9hQLVXF2p6Nz5shTmeX3i1r9OggUlA1ifRNLqSM7xMCGP8xlzlfTy1WuoBh8WPnZQgG+8YsJ+aj4ELSWXFgJKnOGBW26wM3spt+OH+VXv2yTGV/zbCyZqxjJ5q39fAEIAIgLL9i2PX+Y1Kxe/bGCTKwjgwo4L6rgdn3xMBY50WXV6nY6tMhxU8WrgKZxbH7BZwLzAbXzXfd13lzkpsLZWzKAxCYk+JWBH+aBc+eVi3Ki/JDsYLR0+yJ2d+q0QyA+2BAT2/diioeqSJwO4E3Vo1wgAbssAKwGKw9DUh9kkBVaGgSUglhPnEOXjZFhxHi4ufIA4F/Vv6jk/hpro1DlNSYOtThEkbwx+4HQrYUdF+Oadf24/5c5KZxDP49hV8DBvVOaakULnUzeL3vb/8NiukNFOfq/YSk97S3C38lPvklbw64lTedp7/U6DMGupDvjQlrB4cg9E2QZ9smDbMNZvL4s99Z1kp6fJlig0BoCo2lgCnKz3bMlU8C/guDTzpVVDpCjnxsfbqxpE3Xh3x583zKx8ujxp0QAMgwbPqni9xiUk67sxiRpdhFrzJhHmgPlExowfAt+20upBpw/AJE5+cntupdqlSa08jZBPOeSrsg+GxRYO8xkcqO34DZy/0boX97lCv7jGH9mt4=
